# Generated by Django 6.0 on 2026-01-07 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(default='Du bist ein hilfreicher Experte. Beantworte Fragen basierend auf den bereitgestellten Dokumenten. Zitiere relevante Quellen.')),
                ('is_indexed', models.BooleanField(default=False)),
                ('document_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experte',
                'verbose_name_plural': 'Experten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpertConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Neue Konversation', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='knowledgebase.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Experten-Konversation',
                'verbose_name_plural': 'Experten-Konversationen',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledgebase/%Y/%m/')),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'Verarbeitung'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledgebase.expert')),
            ],
            options={
                'verbose_name': 'Experten-Dokument',
                'verbose_name_plural': 'Experten-Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Benutzer'), ('assistant', 'Assistent')], max_length=10)),
                ('content', models.TextField()),
                ('source_chunks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledgebase.expertconversation')),
            ],
            options={
                'verbose_name': 'Experten-Nachricht',
                'verbose_name_plural': 'Experten-Nachrichten',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('chroma_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledgebase.expertdocument')),
            ],
            options={
                'verbose_name': 'Dokument-Chunk',
                'verbose_name_plural': 'Dokument-Chunks',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['chroma_id'], name='knowledgeba_chroma__2bbe86_idx')],
            },
        ),
    ]
