# Generated by Django 6.0 on 2026-01-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_openrouter_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
