# Generated by Django 6.0 on 2026-01-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_add_conversation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🤖', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('system_prompt', models.TextField()),
                ('enabled_tools', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_helpers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_helpers',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='ai.helper'),
        ),
    ]
