// System Architecture Library for Excalidraw
// Contains reusable components for system architecture diagrams

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type LibraryItem = any

// Helper to generate unique IDs
const generateId = () => Math.random().toString(36).substring(2, 15)
const randomSeed = () => Math.floor(Math.random() * 100000)

// Server rack with horizontal lines
function createServer(label: string) {
  const groupId = generateId()
  return [
    // Main box
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 100,
      height: 120,
      strokeColor: '#495057',
      backgroundColor: '#343a40',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Slot 1
    {
      type: 'rectangle',
      id: generateId(),
      x: 8,
      y: 10,
      width: 84,
      height: 20,
      strokeColor: '#868e96',
      backgroundColor: '#495057',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // LED 1
    {
      type: 'ellipse',
      id: generateId(),
      x: 78,
      y: 15,
      width: 10,
      height: 10,
      strokeColor: '#51cf66',
      backgroundColor: '#51cf66',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Slot 2
    {
      type: 'rectangle',
      id: generateId(),
      x: 8,
      y: 38,
      width: 84,
      height: 20,
      strokeColor: '#868e96',
      backgroundColor: '#495057',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // LED 2
    {
      type: 'ellipse',
      id: generateId(),
      x: 78,
      y: 43,
      width: 10,
      height: 10,
      strokeColor: '#51cf66',
      backgroundColor: '#51cf66',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Slot 3
    {
      type: 'rectangle',
      id: generateId(),
      x: 8,
      y: 66,
      width: 84,
      height: 20,
      strokeColor: '#868e96',
      backgroundColor: '#495057',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a5',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // LED 3
    {
      type: 'ellipse',
      id: generateId(),
      x: 78,
      y: 71,
      width: 10,
      height: 10,
      strokeColor: '#ffd43b',
      backgroundColor: '#ffd43b',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a6',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 50,
      y: 96,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a7',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Database cylinder
function createDatabase(label: string) {
  const groupId = generateId()
  return [
    // Bottom ellipse (behind)
    {
      type: 'ellipse',
      id: generateId(),
      x: 0,
      y: 70,
      width: 80,
      height: 24,
      strokeColor: '#1864ab',
      backgroundColor: '#1864ab',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Left side
    {
      type: 'line',
      id: generateId(),
      x: 0,
      y: 12,
      width: 0,
      height: 70,
      strokeColor: '#1864ab',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [0, 70]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Right side
    {
      type: 'line',
      id: generateId(),
      x: 80,
      y: 12,
      width: 0,
      height: 70,
      strokeColor: '#1864ab',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [0, 70]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Body fill
    {
      type: 'rectangle',
      id: generateId(),
      x: 1,
      y: 12,
      width: 78,
      height: 70,
      strokeColor: 'transparent',
      backgroundColor: '#339af0',
      fillStyle: 'solid',
      strokeWidth: 0,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Top ellipse
    {
      type: 'ellipse',
      id: generateId(),
      x: 0,
      y: 0,
      width: 80,
      height: 24,
      strokeColor: '#1864ab',
      backgroundColor: '#74c0fc',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Middle line 1
    {
      type: 'ellipse',
      id: generateId(),
      x: 0,
      y: 25,
      width: 80,
      height: 14,
      strokeColor: '#1864ab',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 40,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a5',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 55,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a6',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// User/Person icon
function createUser(label: string) {
  const groupId = generateId()
  return [
    // Head
    {
      type: 'ellipse',
      id: generateId(),
      x: 20,
      y: 0,
      width: 40,
      height: 40,
      strokeColor: '#495057',
      backgroundColor: '#adb5bd',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Body
    {
      type: 'ellipse',
      id: generateId(),
      x: 5,
      y: 45,
      width: 70,
      height: 50,
      strokeColor: '#495057',
      backgroundColor: '#adb5bd',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 100,
      width: 0,
      height: 20,
      strokeColor: '#495057',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Cloud shape
function createCloud(label: string) {
  const groupId = generateId()
  return [
    // Bottom large ellipse
    {
      type: 'ellipse',
      id: generateId(),
      x: 10,
      y: 40,
      width: 120,
      height: 50,
      strokeColor: '#5c7cfa',
      backgroundColor: '#748ffc',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Left bump
    {
      type: 'ellipse',
      id: generateId(),
      x: 0,
      y: 25,
      width: 50,
      height: 45,
      strokeColor: '#5c7cfa',
      backgroundColor: '#748ffc',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Middle bump (big)
    {
      type: 'ellipse',
      id: generateId(),
      x: 30,
      y: 0,
      width: 70,
      height: 55,
      strokeColor: '#5c7cfa',
      backgroundColor: '#748ffc',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Right bump
    {
      type: 'ellipse',
      id: generateId(),
      x: 85,
      y: 20,
      width: 45,
      height: 40,
      strokeColor: '#5c7cfa',
      backgroundColor: '#748ffc',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 70,
      y: 55,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Load Balancer - two arrows splitting
function createLoadBalancer() {
  const groupId = generateId()
  return [
    // Circle
    {
      type: 'ellipse',
      id: generateId(),
      x: 0,
      y: 0,
      width: 80,
      height: 80,
      strokeColor: '#f76707',
      backgroundColor: '#fd7e14',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Left arrow line
    {
      type: 'line',
      id: generateId(),
      x: 20,
      y: 25,
      width: 20,
      height: 15,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 3,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[20, 15], [0, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: 'arrow',
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Right arrow line
    {
      type: 'line',
      id: generateId(),
      x: 40,
      y: 25,
      width: 20,
      height: 15,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 3,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 15], [20, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: 'arrow',
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Bottom arrow
    {
      type: 'line',
      id: generateId(),
      x: 40,
      y: 40,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 3,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 20], [0, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: 'arrow',
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 88,
      width: 0,
      height: 16,
      strokeColor: '#f76707',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: 'LB',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      containerId: null,
      originalText: 'LB',
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Container/Docker
function createContainer(label: string) {
  const groupId = generateId()
  return [
    // Main container box
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 15,
      width: 100,
      height: 70,
      strokeColor: '#1098ad',
      backgroundColor: '#15aabf',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Top handle left
    {
      type: 'rectangle',
      id: generateId(),
      x: 20,
      y: 0,
      width: 15,
      height: 20,
      strokeColor: '#1098ad',
      backgroundColor: '#1098ad',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Top handle middle
    {
      type: 'rectangle',
      id: generateId(),
      x: 42,
      y: 0,
      width: 15,
      height: 20,
      strokeColor: '#1098ad',
      backgroundColor: '#1098ad',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Top handle right
    {
      type: 'rectangle',
      id: generateId(),
      x: 64,
      y: 0,
      width: 15,
      height: 20,
      strokeColor: '#1098ad',
      backgroundColor: '#1098ad',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 50,
      y: 50,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Message Queue
function createQueue(label: string) {
  const groupId = generateId()
  return [
    // Queue pipe
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 20,
      width: 120,
      height: 40,
      strokeColor: '#2f9e44',
      backgroundColor: '#40c057',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Message 1
    {
      type: 'rectangle',
      id: generateId(),
      x: 10,
      y: 28,
      width: 24,
      height: 24,
      strokeColor: '#2f9e44',
      backgroundColor: '#b2f2bb',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Message 2
    {
      type: 'rectangle',
      id: generateId(),
      x: 40,
      y: 28,
      width: 24,
      height: 24,
      strokeColor: '#2f9e44',
      backgroundColor: '#b2f2bb',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Message 3
    {
      type: 'rectangle',
      id: generateId(),
      x: 70,
      y: 28,
      width: 24,
      height: 24,
      strokeColor: '#2f9e44',
      backgroundColor: '#b2f2bb',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Arrow out
    {
      type: 'line',
      id: generateId(),
      x: 100,
      y: 40,
      width: 25,
      height: 0,
      strokeColor: '#2f9e44',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [25, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: 'arrow',
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 60,
      y: 68,
      width: 0,
      height: 16,
      strokeColor: '#2f9e44',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a5',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// API Gateway
function createAPIGateway() {
  const groupId = generateId()
  return [
    // Gateway shape (hexagon-ish)
    {
      type: 'diamond',
      id: generateId(),
      x: 0,
      y: 0,
      width: 100,
      height: 60,
      strokeColor: '#862e9c',
      backgroundColor: '#9c36b5',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 50,
      y: 30,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: 'API',
      fontSize: 16,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: 'API',
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Cache/Redis
function createCache(label: string) {
  const groupId = generateId()
  return [
    // Lightning bolt style
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 80,
      height: 70,
      strokeColor: '#e03131',
      backgroundColor: '#ff6b6b',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Lightning bolt
    {
      type: 'line',
      id: generateId(),
      x: 30,
      y: 12,
      width: 20,
      height: 46,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 3,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[15, 0], [0, 20], [12, 20], [5, 46]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 78,
      width: 0,
      height: 16,
      strokeColor: '#e03131',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'top',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Lambda/Function
function createLambda() {
  const groupId = generateId()
  return [
    // Lambda box with angled top
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 80,
      height: 80,
      strokeColor: '#e67700',
      backgroundColor: '#fab005',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Lambda symbol
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 40,
      width: 0,
      height: 40,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: 'λ',
      fontSize: 36,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: 'λ',
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Storage bucket
function createStorage(label: string) {
  const groupId = generateId()
  return [
    // Bucket shape - wider at top
    {
      type: 'rectangle',
      id: generateId(),
      x: 10,
      y: 0,
      width: 80,
      height: 20,
      strokeColor: '#5c940d',
      backgroundColor: '#82c91e',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Body
    {
      type: 'rectangle',
      id: generateId(),
      x: 15,
      y: 18,
      width: 70,
      height: 50,
      strokeColor: '#5c940d',
      backgroundColor: '#a9e34b',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Bottom
    {
      type: 'rectangle',
      id: generateId(),
      x: 20,
      y: 66,
      width: 60,
      height: 14,
      strokeColor: '#5c940d',
      backgroundColor: '#5c940d',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 50,
      y: 43,
      width: 0,
      height: 20,
      strokeColor: '#1e1e1e',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 14,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Firewall/Security
function createFirewall() {
  const groupId = generateId()
  return [
    // Wall
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 20,
      height: 80,
      strokeColor: '#c92a2a',
      backgroundColor: '#e03131',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Bricks
    {
      type: 'line',
      id: generateId(),
      x: 0,
      y: 20,
      width: 20,
      height: 0,
      strokeColor: '#c92a2a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [20, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    {
      type: 'line',
      id: generateId(),
      x: 0,
      y: 40,
      width: 20,
      height: 0,
      strokeColor: '#c92a2a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [20, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    {
      type: 'line',
      id: generateId(),
      x: 0,
      y: 60,
      width: 20,
      height: 0,
      strokeColor: '#c92a2a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [20, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Vertical brick lines
    {
      type: 'line',
      id: generateId(),
      x: 10,
      y: 0,
      width: 0,
      height: 20,
      strokeColor: '#c92a2a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [0, 20]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    {
      type: 'line',
      id: generateId(),
      x: 10,
      y: 40,
      width: 0,
      height: 20,
      strokeColor: '#c92a2a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      points: [[0, 0], [0, 20]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: null,
      groupIds: [groupId],
      frameId: null,
      index: 'a5',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Browser/Web
function createBrowser() {
  const groupId = generateId()
  return [
    // Window frame
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 100,
      height: 80,
      strokeColor: '#495057',
      backgroundColor: '#f8f9fa',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Title bar
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 100,
      height: 20,
      strokeColor: '#495057',
      backgroundColor: '#dee2e6',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Red dot
    {
      type: 'ellipse',
      id: generateId(),
      x: 8,
      y: 6,
      width: 8,
      height: 8,
      strokeColor: '#e03131',
      backgroundColor: '#e03131',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Yellow dot
    {
      type: 'ellipse',
      id: generateId(),
      x: 20,
      y: 6,
      width: 8,
      height: 8,
      strokeColor: '#fab005',
      backgroundColor: '#fab005',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a3',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Green dot
    {
      type: 'ellipse',
      id: generateId(),
      x: 32,
      y: 6,
      width: 8,
      height: 8,
      strokeColor: '#40c057',
      backgroundColor: '#40c057',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a4',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Content area
    {
      type: 'rectangle',
      id: generateId(),
      x: 8,
      y: 28,
      width: 84,
      height: 44,
      strokeColor: '#ced4da',
      backgroundColor: '#ffffff',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a5',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Mobile phone
function createMobile() {
  const groupId = generateId()
  return [
    // Phone body
    {
      type: 'rectangle',
      id: generateId(),
      x: 0,
      y: 0,
      width: 50,
      height: 90,
      strokeColor: '#495057',
      backgroundColor: '#343a40',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: { type: 3 },
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Screen
    {
      type: 'rectangle',
      id: generateId(),
      x: 5,
      y: 10,
      width: 40,
      height: 60,
      strokeColor: '#228be6',
      backgroundColor: '#339af0',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Home button
    {
      type: 'ellipse',
      id: generateId(),
      x: 20,
      y: 75,
      width: 10,
      height: 10,
      strokeColor: '#495057',
      backgroundColor: '#495057',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a2',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Microservice hexagon
function createMicroservice(label: string) {
  const groupId = generateId()
  return [
    // Hexagon using diamond rotated
    {
      type: 'diamond',
      id: generateId(),
      x: 0,
      y: 10,
      width: 80,
      height: 60,
      strokeColor: '#1098ad',
      backgroundColor: '#22b8cf',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      opacity: 100,
      angle: 0,
      groupIds: [groupId],
      frameId: null,
      index: 'a0',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
    // Label
    {
      type: 'text',
      id: generateId(),
      x: 40,
      y: 40,
      width: 0,
      height: 20,
      strokeColor: '#ffffff',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      angle: 0,
      text: label,
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      containerId: null,
      originalText: label,
      autoResize: true,
      lineHeight: 1.25,
      groupIds: [groupId],
      frameId: null,
      index: 'a1',
      roundness: null,
      seed: randomSeed(),
      version: 1,
      versionNonce: randomSeed(),
      isDeleted: false,
      boundElements: null,
      updated: Date.now(),
      link: null,
      locked: false,
    },
  ]
}

// Library items
export const architectureLibraryItems: LibraryItem[] = [
  // Infrastructure
  {
    id: 'arch-server',
    status: 'published',
    elements: createServer('Server'),
    created: Date.now(),
  },
  {
    id: 'arch-database',
    status: 'published',
    elements: createDatabase('DB'),
    created: Date.now(),
  },
  {
    id: 'arch-cache',
    status: 'published',
    elements: createCache('Cache'),
    created: Date.now(),
  },
  {
    id: 'arch-storage',
    status: 'published',
    elements: createStorage('S3'),
    created: Date.now(),
  },

  // Network
  {
    id: 'arch-load-balancer',
    status: 'published',
    elements: createLoadBalancer(),
    created: Date.now(),
  },
  {
    id: 'arch-api-gateway',
    status: 'published',
    elements: createAPIGateway(),
    created: Date.now(),
  },
  {
    id: 'arch-firewall',
    status: 'published',
    elements: createFirewall(),
    created: Date.now(),
  },

  // Compute
  {
    id: 'arch-container',
    status: 'published',
    elements: createContainer('Docker'),
    created: Date.now(),
  },
  {
    id: 'arch-lambda',
    status: 'published',
    elements: createLambda(),
    created: Date.now(),
  },
  {
    id: 'arch-microservice',
    status: 'published',
    elements: createMicroservice('Service'),
    created: Date.now(),
  },

  // Messaging
  {
    id: 'arch-queue',
    status: 'published',
    elements: createQueue('Queue'),
    created: Date.now(),
  },

  // Cloud
  {
    id: 'arch-cloud',
    status: 'published',
    elements: createCloud('Cloud'),
    created: Date.now(),
  },

  // Clients
  {
    id: 'arch-user',
    status: 'published',
    elements: createUser('User'),
    created: Date.now(),
  },
  {
    id: 'arch-browser',
    status: 'published',
    elements: createBrowser(),
    created: Date.now(),
  },
  {
    id: 'arch-mobile',
    status: 'published',
    elements: createMobile(),
    created: Date.now(),
  },
] as unknown as LibraryItem[]
