# Generated by Django 6.0 on 2026-01-04 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTimer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='active_timer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('paused_time', models.BigIntegerField(default=0)),
                ('is_running', models.BooleanField(default=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_timers', to='timetracking.project')),
            ],
            options={
                'verbose_name': 'Active Timer',
                'verbose_name_plural': 'Active Timers',
            },
        ),
    ]
