# Generated by Django 6.0 on 2026-01-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Deutschland', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('next_invoice_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
