# Generated by Django 6.0 on 2026-01-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='dock_order',
            field=models.JSONField(blank=True, default=list, help_text='Order of apps in the dock'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='enabled_apps',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled app IDs'),
        ),
    ]
