# Generated by Django 6.0 on 2026-01-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai_game', models.BooleanField(default=False)),
                ('ai_difficulty', models.IntegerField(default=10)),
                ('player_color', models.CharField(default='white', max_length=5)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('pgn', models.TextField(blank=True)),
                ('moves', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('waiting', 'Warte auf Gegner'), ('active', 'Aktiv'), ('checkmate', 'Schachmatt'), ('stalemate', 'Patt'), ('draw', 'Remis'), ('resigned', 'Aufgegeben'), ('timeout', 'Zeit abgelaufen')], default='waiting', max_length=20)),
                ('time_control', models.IntegerField(blank=True, null=True)),
                ('white_time_remaining', models.IntegerField(blank=True, null=True)),
                ('black_time_remaining', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('black_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chess_games_as_white', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chess_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schachspiel',
                'verbose_name_plural': 'Schachspiele',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChessInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('accepted', 'Angenommen'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chess_invites', to=settings.AUTH_USER_MODEL)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='chess.chessgame')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chess_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schach-Einladung',
                'verbose_name_plural': 'Schach-Einladungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
