# Generated by Django 6.0 on 2026-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='show_in_sidebar',
            field=models.BooleanField(default=True),
        ),
    ]
