# Generated by Django 6.0 on 2026-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_folder_show_in_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
