# Generated by Django 6.0 on 2026-01-10 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextStyleFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('font_family', models.CharField(default='SF Pro Display', max_length=100)),
                ('font_size', models.PositiveIntegerField(default=48)),
                ('font_weight', models.PositiveIntegerField(default=400)),
                ('font_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_align', models.CharField(default='center', max_length=10)),
                ('text_effects', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_style_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
